[package]
name = "day20"
version = "0.1.0"
authors = ["Kasper Furnes Bernhoff <kb@kfbi.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primes = "0.2.3"

[[bin]]
name = "day20"
path = "main.rs"
